"""add users, branch_memberships, branch contact fields

Revision ID: aac5277e85ae
Revises: 2601b254964b
Create Date: 2026-09-03 05:12:07.831745
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aac5277e85ae'
down_revision: Union[str, None] = '2601b254964b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('branch_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('branch_admin', 'staff')", name='ck_branch_membership_role'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'branch_id', name='uq_branch_membership_user_branch')
    )
    op.create_index(op.f('ix_branch_memberships_branch_id'), 'branch_memberships', ['branch_id'], unique=False)
    op.create_index(op.f('ix_branch_memberships_user_id'), 'branch_memberships', ['user_id'], unique=False)
    op.add_column('branches', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('branches', sa.Column('phone', sa.String(length=30), nullable=True))
    op.add_column('branches', sa.Column('timezone', sa.String(length=50), server_default='Asia/Jakarta', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branches', 'timezone')
    op.drop_column('branches', 'phone')
    op.drop_column('branches', 'address')
    op.drop_index(op.f('ix_branch_memberships_user_id'), table_name='branch_memberships')
    op.drop_index(op.f('ix_branch_memberships_branch_id'), table_name='branch_memberships')
    op.drop_table('branch_memberships')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
